### ISSUE TITLE
nohup: ignoring input and appending output to 'nohup.out'

### ISSUE THREAD

**Issue by Err0rXG** [danicuestasuarez/NMapGUI#26] opened 2018-08-05 21:35 UTC

**Comment by Err0rXG** [comment] 2018-08-05 21:35
nohup: ignoring input and appending output to 'nohup.out'

**Comment by daniel-cues** [comment] 2018-08-07 11:49
Leaving unassigned and invalid until more information is provided

**Comment by JackTheGilis** [comment] 2018-09-24 09:39
same here, I got :
nohup: ignoring input and appending output to 'nohup.out'

**Comment by daniel-cues** [comment] 2018-09-24 09:53
@JetPro55 @JackTheGilis That's expected behavior. That means that you can close the terminal and use nmapgui without it. If you'd rather see the output on console but not being able to close it, you could just run 
`java -jar nmapGUI-0.6.1-snapshot.jar`

**Comment by JackTheGilis** [comment] 2018-09-24 10:50
This is what i get, after click StartNMapGUI, Go button stil disable, i test it on 2 leptop with standart Kali Linux installed.
![screenshot_1](https://user-images.githubusercontent.com/28474591/45948353-2ebb8200-c02a-11e8-915b-3f74aa322132.png)

**Comment by daniel-cues** [comment] 2018-09-24 10:57
Please copy and paste the whole stack trace

**Comment by JackTheGilis** [comment] 2018-09-24 10:58
root@hexagon:~# java -jar nmapGUI-0.6.1-SNAPSHOT.jar
java.io.FileNotFoundException: /tmp/nmap-scan_2018-09-24_06-41-09.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:196)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:139)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:94)
	at java.base/java.io.FileReader.<init>(FileReader.java:58)
	at com.uniovi.nmapgui.executor.CommandExecutorImpl.readXML(CommandExecutorImpl.java:167)
	at com.uniovi.nmapgui.executor.CommandExecutorImpl$1.run(CommandExecutorImpl.java:86)
	at java.base/java.lang.Thread.run(Thread.java:844)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.3.RELEASE)

2018-09-24 06:41:33.171  INFO 2660 --- [WT-EventQueue-0] o.s.boot.SpringApplication               : Starting application on hexagon with PID 2660 (/root/nmapGUI-0.6.1-SNAPSHOT.jar started by root in /root)
2018-09-24 06:41:33.201  INFO 2660 --- [WT-EventQueue-0] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/root/nmapGUI-0.6.1-SNAPSHOT.jar!/BOOT-INF/lib/groovy-2.4.10.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-09-24 06:41:38.294  INFO 2660 --- [WT-EventQueue-0] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@7dd77054: startup date [Mon Sep 24 06:41:38 EDT 2018]; root of context hierarchy
2018-09-24 06:41:45.476  INFO 2660 --- [WT-EventQueue-0] trationDelegate$BeanPostProcessorChecker : Bean 'NMapGuiApplication' of type [com.uniovi.nmapgui.NMapGuiApplication$$EnhancerBySpringCGLIB$$525c406c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-09-24 06:41:50.206  INFO 2660 --- [WT-EventQueue-0] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2018-09-24 06:41:50.298  INFO 2660 --- [WT-EventQueue-0] o.apache.catalina.core.StandardService   : Starting service Tomcat
2018-09-24 06:41:50.302  INFO 2660 --- [WT-EventQueue-0] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.14
2018-09-24 06:41:51.929  INFO 2660 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-09-24 06:41:51.936  INFO 2660 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 13676 ms
2018-09-24 06:41:56.461  INFO 2660 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2018-09-24 06:41:56.486  INFO 2660 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-09-24 06:41:56.493  INFO 2660 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-09-24 06:41:56.494  INFO 2660 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-09-24 06:41:56.495  INFO 2660 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-09-24 06:41:56.915  WARN 2660 --- [WT-EventQueue-0] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webController' defined in URL [jar:file:/root/nmapGUI-0.6.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/uniovi/nmapgui/WebController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.uniovi.nmapgui.WebController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
2018-09-24 06:41:56.925  INFO 2660 --- [WT-EventQueue-0] o.apache.catalina.core.StandardService   : Stopping service Tomcat
2018-09-24 06:41:57.050  INFO 2660 --- [WT-EventQueue-0] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-09-24 06:41:57.092 ERROR 2660 --- [WT-EventQueue-0] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webController' defined in URL [jar:file:/root/nmapGUI-0.6.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/uniovi/nmapgui/WebController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.uniovi.nmapgui.WebController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1155) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar!/:1.5.3.RELEASE]
	at com.uniovi.nmapgui.NMapGuiApplication.mainExec(NMapGuiApplication.java:16) [classes!/:0.6.1-SNAPSHOT]
	at com.uniovi.nmapgui.NMapLoaderWindow$2.actionPerformed(NMapLoaderWindow.java:122) [classes!/:0.6.1-SNAPSHOT]
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967) [na:na]
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308) [na:na]
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) [na:na]
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) [na:na]
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:269) [na:na]
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578) [na:na]
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343) [na:na]
	at java.desktop/java.awt.Component.processEvent(Component.java:6343) [na:na]
	at java.desktop/java.awt.Container.processEvent(Container.java:2259) [na:na]
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961) [na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317) [na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793) [na:na]
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) [na:na]
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539) [na:na]
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480) [na:na]
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2303) [na:na]
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758) [na:na]
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793) [na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766) [na:na]
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97) [na:na]
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717) [na:na]
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89) [na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99) [na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739) [na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737) [na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) [na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89) [na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736) [na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199) [na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:na]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [na:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.uniovi.nmapgui.WebController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	... 54 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.uniovi.nmapgui.WebController.<init>(WebController.java:34) ~[classes!/:0.6.1-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.8.RELEASE.jar!/:4.3.8.RELEASE]
	... 56 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[nmapGUI-0.6.1-SNAPSHOT.jar:0.6.1-SNAPSHOT]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	... 62 common frames omitted

Exception in thread "AWT-EventQueue-0" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webController' defined in URL [jar:file:/root/nmapGUI-0.6.1-SNAPSHOT.jar!/BOOT-INF/classes!/com/uniovi/nmapgui/WebController.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.uniovi.nmapgui.WebController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1155)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151)
	at com.uniovi.nmapgui.NMapGuiApplication.mainExec(NMapGuiApplication.java:16)
	at com.uniovi.nmapgui.NMapLoaderWindow$2.actionPerformed(NMapLoaderWindow.java:122)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:269)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6578)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3343)
	at java.desktop/java.awt.Component.processEvent(Component.java:6343)
	at java.desktop/java.awt.Container.processEvent(Container.java:2259)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4961)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2317)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4539)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4480)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2303)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2758)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4793)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:99)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.uniovi.nmapgui.WebController]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147)
	... 54 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.uniovi.nmapgui.WebController.<init>(WebController.java:34)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 56 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 62 more

**Comment by daniel-cues** [comment] 2018-09-24 11:05
Which java version are you using?

**Comment by JackTheGilis** [comment] 2018-09-24 11:08
root@hexagon:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)

and 

root@Node01:~# java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Debian-1)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Debian-1, mixed mode)

**Comment by daniel-cues** [comment] 2018-09-24 11:19
Seems that java 9 has moved some classes around. Linking and closing this issue as it is the same as #25. The only workaround I can offer as of now is downgrading to Java 8. Also, I'm adding Java8 as a requirement in the readme.
https://github.com/danicuestasuarez/NMapGUI/issues/25#issuecomment-411030771

Have a good day!

**Closed as completed by daniel-cues** 2018-09-24 11:19 UTC
Labels: duplicate

**Comment by JackTheGilis** [comment] 2018-09-24 11:38
> Seems that java 9 has moved some classes around. Linking and closing this issue as it is the same as #25. The only workaround I can offer as of now is downgrading to Java 8. Also adding Java8 as a requirement in the readme.
> [#25 (comment)](https://github.com/danicuestasuarez/NMapGUI/issues/25#issuecomment-411030771)
> 
> Have a good day!

I just want to confirm, after downgrade to Java 8 It's Working now, Thankyou.
